import Head from 'next/head'
import React from 'react';
import ContentService from '../services/ContentService/ContentService';

interface IProps {
    headers: Array<{label: string, target: string}>
}

class Index extends React.Component<IProps, any> {
    render() {
        return (
            <>
                <Head>
                    <title>LammensJ</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <main>
                    <h1>Welcome to LammensJ</h1>
                </main>
            </>
        )
    }
}

export default Index;

export const getStaticProps = async () => {
    const contentService: ContentService = new ContentService();
    const headers: Array<{label: string, target: string}> = contentService.getHeaders();

    return {props: {headers}};
}
